basePath: /api
definitions:
  model.Error:
    properties:
      error: {}
    type: object
  model.Response:
    properties:
      body: {}
    type: object
  model.User:
    properties:
      about:
        type: string
      email:
        type: string
      fullname:
        type: string
      nickname:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: DB project server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: DB project API
  version: "1.0"
paths:
  /user/{nickname}/create:
    post:
      consumes:
      - application/json
      description: Creates User
      operationId: CreateUser
      parameters:
      - description: nickname of user
        in: path
        name: nickname
        required: true
        type: string
      - description: User params
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/model.User'
      produces:
      - application/json
      responses:
        "201":
          description: OK
          schema:
            $ref: '#/definitions/model.Response'
        "400":
          description: Bad request - Problem with the request
          schema:
            $ref: '#/definitions/model.Error'
        "409":
          description: Conflict - User already exists
          schema:
            $ref: '#/definitions/model.Error'
        "500":
          description: Internal Server Error - Request is valid but operation failed
            at server side
          schema:
            $ref: '#/definitions/model.Error'
      summary: Creates User
      tags:
      - User
swagger: "2.0"
